name: CI

on: [push, workflow_dispatch]

Jobs:

build:

runs-on: windows-latest

name: Download

run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

name: Extract

run:\ngrok\ngrok.exe authtoken SEnv: NGROK_AUTH_TOKEN

steps:

run: Expand-Archive ngrok.zip


name: Auth


env:


NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

name: Enable TS

name: Create Tunnel

run:\ngrok\ngrok.exe tcp 3389

run: Set-ItemProperty Path "HKLM:\System\CurrentControlSet\Control\Terminal Server-name "DenyTSConnections" -Value

run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

run: Set-ItemProperty Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp-name "UserAuthentication" -Value 1

run: Set-LocalUser Name "runneradmin" -Password (Convert
